version: "3.9"
services:
  app:
    build: ./images/app
    image: malta-app
    depends_on:
      - api
    ports:
      - "80:80"

  api:
    build: ./images/api
    image: malta-api
    environment:
      - PORT0=8080
    ports:
      - "8000:8080"
