version: "3.9"
services:
  app:
    build: ./app
    image: malta-app
    depends_on:
      - api
    ports:
      - "80:80"

  api:
    build: ./api
    image: malta-api
    environment:
      - PORT0=8080
      - DJANGO_SU_PASSWORD=admin
    ports:
      - "8000:8080"
    volumes:
      - ./api/src:/usr/src/app

  extractToText:
    container_name: extractToText
    image: 925340840713.dkr.ecr.us-east-1.amazonaws.com/malta_to_text:latest
    build:
      context: ./extract-to-text
    env_file:
      - ./.env
    environment:
      - TARGET_BUCKET=malta-lake
    ports:
      - 9000:8080

  toCorpus:
    container_name: toCorpus
    image: 925340840713.dkr.ecr.us-east-1.amazonaws.com/malta_to_corpus:latest
    build:
      context: ./to-corpus
    env_file:
      - ./.env
    environment:
      - TARGET_BUCKET=malta-corpus
    ports:
      - 9001:8080
