version: "3.9"
services:
  app:
    build: ./app
    image: malta-app
    depends_on:
      - api
    ports:
      - "80:80"

  api:
    build: ./api
    image: malta-api
    environment:
      - PORT0=8080
      - DJANGO_SU_PASSWORD=admin
    ports:
      - "8000:8080"
    volumes:
      - ./api/src:/usr/src/app
