# Generated by Django 3.1.5 on 2021-01-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=200)),
                ('office', models.CharField(blank=True, max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('prime', models.CharField(blank=True, max_length=200)),
                ('subs', models.CharField(blank=True, max_length=200)),
                ('staff_size', models.IntegerField(blank=True, null=True)),
                ('pop_start', models.DateField(blank=True, null=True)),
                ('pop_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'db_table': 'cv',
            },
        ),
    ]
