# Generated by Django 3.1.5 on 2021-01-08 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to='cv.cv')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to='documents.document')),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='documents',
            field=models.ManyToManyField(related_name='cvs', through='cv.CVDocument', to='documents.Document'),
        ),
    ]
